const chrome = require('.')
try {
  chrome({ show: false })
  .viewport(1900, 1000)
  .useragent('Mozilla/5.0 Chrome/59.0.3071.115 Mobile Safari/537.36')
  .goto('https://www.baidu.com/')
  .wait('body')
  .html('1.html')
  .insert('input#kw', 'hello world\r')
  .wait('.c-container a')
  .screenshot('1.jpg')
  .evaluate(() => document.querySelector('.c-container a').href)
  .then(function (url) {
    console.log(url)
    return chrome().goto(url).viewport(1900, 1000)
  })
  .wait('[id^="highlighter_"]')
  .pdf('1.pdf')
  .evaluate(() => document.querySelectorAll('.para-title.level-3')[9].nextElementSibling.querySelector('.code').textContent)
  .then((code) => console.log(code))
  .url()
  .then((url) => console.log(url))
} catch (e) {
  console.log(e)
}
